version: '3'

volumes:
  node_modules:
  vendor:
  certbot-etc:
  certbot-var:

services:

  app:
    container_name: app
    build: .
    restart: "always"
    working_dir: /app
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./docker/xdebug.local.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro

      - ./app:/app/app:cached
      - ./i18n:/app/i18n:cached
      - ./assets/dynamic:/app/assets/dynamic:cached
      - ./www:/app/www:cached
      - ./log:/app/log:cached
      - ./temp:/app/temp:cached
      - ./vendor:/app/vendor:cached
    expose:
      - 9000
    networks:
      - wakers


  nginx:
    image: nginx:1.15.4-alpine
    restart: "always"
    container_name: nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      # nginx potřebuje vytáhnout data vygenerované v app containeru
      - ./app:/app/app:cached
      - ./assets/dynamic:/app/assets/dynamic:cached
      - ./www:/app/www:cached
      - ./log:/app/log:cached
      - ./temp:/app/temp:cached
      - ./vendor:/app/vendor:cached
      # https
      #- ./web-root:/app/www
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    networks:
      - wakers
    ports:
      - 80:80


  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./www:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email info@wakers.cz --agree-tos --no-eff-email --staging -d ${HTTPS_DOMAIN}  -d ${HTTPS_DOMAIN_WWW}


  mariadb:
    container_name: mariadb
    image: mariadb:10.1.34
    restart: "always"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON
    volumes:
      # mariadb ukládá db mimo container
      - ./docker/database.local:/var/lib/mysql:cached
    ports:
      - 3306:3306
    networks:
      - wakers


  adminer:
    container_name: adminer
    image: dockette/adminer:dg
    restart: "always"
    ports:
      - 9876:80
    networks:
      - wakers


  composer:
    container_name: composer
    image: composer:1.7.2
    restart: "no"
    tty: true
    command: tail
    volumes:
      - ./vendor/.temp-fix/app:/app:cached
      - vendor:/app/vendor # exclude from fix
      - ./vendor:/app/vendor:delegated
    networks:
      - wakers


  nodejs:
    container_name: nodejs
    image: node:8.12
    restart: "no"
    tty: true
    command: tail
    working_dir: /app
    volumes:
      - ./node_modules/.temp-fix:/app:cached
      - node_modules:/app/node_modules # exclude from fix
      - ./node_modules:/app/node_modules:delegated

      # output
      - ./www:/app/www:cached

      # webpack
      - ./webpack.config.js:/app/webpack.config.js:cached
      - ./webpack:/app/webpack:cached

      # static assets
      - ./assets/static:/app/assets/static:delegated

      - ./vendor/wakerscz/cms-base-module/src/assets:/app/vendor/wakerscz/cms-base-module/src/assets:delegated
      - ./vendor/wakerscz/cms-user-module/src/assets:/app/vendor/wakerscz/cms-user-module/src/assets:delegated
      - ./vendor/wakerscz/cms-onpage-module/src/assets:/app/vendor/wakerscz/cms-onpage-module/src/assets:delegated
      - ./vendor/wakerscz/cms-page-module/src/assets:/app/vendor/wakerscz/cms-page-module/src/assets:delegated
      - ./vendor/wakerscz/cms-lang-module/src/assets:/app/vendor/wakerscz/cms-lang-module/src/assets:delegated
      - ./vendor/wakerscz/cms-category-module/src/assets:/app/vendor/wakerscz/cms-category-module/src/assets:delegated
      - ./vendor/wakerscz/cms-structure-module/src/assets:/app/vendor/wakerscz/cms-structure-module/src/assets:delegated

      - ./i18n:/app/i18n:delegated
    networks:
      - wakers

  sftp:
    container_name: sftp
    image: atmoz/sftp:alpine-3.7
    volumes:
      - ./assets/dynamic:/home/wakerscms/assets/dynamic
      #- ./temp/cache:/home/wakerscms/temp/cache
      - ./log:/home/wakerscms/log
    ports:
      - "2222:22"
    command: wakerscms:${SFTP_PASSWORD}:1001
    networks:
      - wakers


networks:
  wakers: