version: '3'

services:

  app:
    container_name: app
    build: .
    restart: "always"
    working_dir: /app
    volumes:
      # PHP Configs
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro

      # Application
      - ./app:/app/app:cached
      - ./i18n:/app/i18n:cached
      - ./assets/dynamic:/app/assets/dynamic:cached
      - ./www:/app/www:cached
      - ./log:/app/log:cached
      - ./temp:/app/temp:cached
      - ./vendor:/app/vendor:cached
    expose:
      - 9000
    networks:
      - wakers-network


  nginx:
    image: nginx:1.15.4-alpine
    restart: "always"
    container_name: nginx
    volumes:
      # Nginx config
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/servers/production.conf:/etc/nginx/servers/production.conf:ro
      - ./docker/nginx/servers/development.conf:/etc/nginx/servers/development.conf:ro

      # Certbot certificates
      - ./docker/certbot.local/conf:/etc/letsencrypt:cached
      - ./docker/certbot.local/www:/var/www/certbot:cached

      # Application
      - ./app:/app/app:cached
      - ./assets/dynamic:/app/assets/dynamic:cached
      - ./www:/app/www:cached
      - ./log:/app/log:cached
      - ./temp:/app/temp:cached
      - ./vendor:/app/vendor:cached
    networks:
      - wakers-network
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - app


  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      # Certbot certificates
      - ./docker/certbot.local/conf:/etc/letsencrypt:cached
      - ./docker/certbot.local/www:/var/www/certbot:cached
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - wakers-network
    depends_on:
      - nginx


  mariadb:
    container_name: mariadb
    image: mariadb:10.1.34
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON
    volumes:
      # Mariadb folder
      - ./docker/mariadb.local:/var/lib/mysql:cached
    #ports:
      #- 3306:3306
    networks:
      - wakers-network


  adminer:
    container_name: adminer
    image: dockette/adminer:dg
    restart: "always"
    ports:
      - 9876:80
    networks:
      - wakers-network


  sftp:
    container_name: sftp
    restart: "always"
    image: atmoz/sftp:alpine-3.7
    volumes:
      - ./assets/dynamic:/home/wakerscms/assets/dynamic
      #- ./temp/cache:/home/wakerscms/temp/cache
      - ./log:/home/wakerscms/log
      #- ./www/temp:/home/wakerscms/www/temp
    ports:
      - "2222:22"
    command: wakerscms:${SFTP_PASSWORD}:1001
    networks:
      - wakers-network


networks:
  wakers-network: